/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHead: typeof import('./inertia/components/AppHead.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    FormInput: typeof import('./inertia/components/FormInput.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Sonner: typeof import('./inertia/components/ui/sonner/Sonner.vue')['default']
    Toast: typeof import('./inertia/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./inertia/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./inertia/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./inertia/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./inertia/components/ui/toast/Toaster.vue')['default']
    ToastManager: typeof import('./inertia/components/ToastManager.vue')['default']
    ToastProvider: typeof import('./inertia/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./inertia/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./inertia/components/ui/toast/ToastViewport.vue')['default']
  }
}
